SELECT * FROM DEPARTMENT INNER JOIN EMPLOYEE
ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID and DEPARTMENT.NAME = ' Financiero';--> HACE UNA UNION EMPLOYEE CON DEPARTMENT Y MUESTRA LOS DEPARTAMENTOS
											 --> TANTO EN LA TABLA DEPARTAMENTOS COMO EN EMPLOYEE.