SELECT * FROM product-->INNER JOIN PARA PODER SACAR QUE COMPRO? CUANTO LE COSTOY? EL CLIENTE QUE LO COMPRO?
INNER JOIN PRODUCTXCLIENT ON PRODUCTXCLIENT.PRODUCT_ID = product.PRODUCT_ID and PRODUCTXCLIENT.CLIENT_ID = 2;

