SELECT client.name, COUNT(PRODUCTXCLIENT.CLIENT_ID)
FROM (pRODUCTXCLIENT INNER JOIN client ON pRODUCTXCLIENT.PRODUCT_ID = CLIENT.CLIENT_ID)
GROUP BY name HAVING COUNT(pRODUCTXCLIENT.PRODUCT_ID) >= 3;