SELECT * FROM EMPLOYEE;--> SOLO PARA QUE SE VEA EL ANTES Y EL DESPUES DE BORRAR

DELETE FROM EMPLOYEE WHERE FIRST_NAME = 'Luis';-->ELIMINAR UN EMPLEADO

SELECT * FROM EMPLOYEE;--> SOLO PARA QUE SE VEA EL ANTES Y EL DESPUES DE BORRAR