update EMPLOYEE set FIRST_NAME= 'Bernal'  where EMPLOYEE_ID = 4; --> ACTUALIZAR UN NOMBRE POR BERNAL

SELECT FIRST_NAME FROM EMPLOYEE WHERE EMPLOYEE_ID = 4; --> VER QUE SE ACTUALIZARA BIEN EL NOMBRE