create or replace
TRIGGER insert_FEC_CREACION
       BEFORE INSERT
       ON GE.empleado FOR EACH ROW
BEGIN
  :NEW.USUARIO_CREACION:= USER;
  :NEW.FEC_CREACION:= SYSDATE;
END;

create or replace
TRIGGER insert_FEC_ULTIMA_MODIFICACION
       BEFORE INSERT
       ON GE.empleado FOR EACH ROW
BEGIN
  :NEW.USUARIO_ULTIMA_MODIFICACION:= USER;
  :NEW.FEC_ULTIMA_MODIFICACION:= SYSDATE;
END;